name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    name: "Deploy Frontend to Render"
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger deploy hook"
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_FRONTEND }}

  deploy-api:
    name: "Deploy API to Render"
    runs-on: ubuntu-latest
    steps:
      - name: "Trigger deploy hook"
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_API }}
